config/routes.rb
Rails.application.routes.draw do
    resources :tweet_clones do
      collection do
        post :confirm
      end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet_clone.rb
class TweetClone < ApplicationRecord
  validates :content, length: {in:1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweet_clones_controller.rb
class TweetClonesController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  def index
    @tweetposts = TweetClone.all
  end
  def new
    @tweet_clone = TweetClone.new
  end
  def create
    @tweet_clone = TweetClone.new(tweet_params)
    if params[:back]
      render :new
    else
      if @tweet_clone.save
        redirect_to tweet_clones_path, notice: "投稿を作成しました"
      else
        render :new
      end
    end
  end
  def show
  end
  def edit
  end
  def update
    if @tweet_clone.update(tweet_params)
      redirect_to tweet_clone_path, notice: "投稿を編集しました"
    else
      render :edit
    end
  end
  def destroy
    @tweet_clone.destroy
    redirect_to tweet_clones_path, notice: "投稿をを削除しました"
  end
  def confirm
    @tweet_clone = TweetClone.new(tweet_params)
    render :new if @tweet_clone.invalid?  #後置if文によるバリデーション設定
  end
  private
  def tweet_params
    params.require(:tweet_clone).permit(:content) #ストロングパラメータにし、さらにprivateメソッド配下にする
  end
  #idをキーとして値を取得する共通メソッドを定義する
  def set_tweet
    @tweet_clone = TweetClone.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweet_clones_helper.rb
module TweetClonesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_tweet_clones_path
    elsif action_name == 'edit'
      tweet_clone_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweet_clones/_form.html.erb
<%= form_with(model: @tweet_clone, local: true,url: choose_new_or_edit ) do |form| %>
  <% if @tweet_clone.errors.any? %>
    <div id="error_explanation">
      <h2><%= @tweet_clone.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @tweet_clone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="tweet_content">
    <%= form.label :投稿内容 %>
    <br>
    <%= form.text_area :content %>
  </div>
  <div class="tweet_content">
  <%= form.submit  value = "この投稿でつぶやく" %>
  </div>
<% end %>
  <div class = "link_text">
<%= link_to '投稿一覧', tweet_clones_path %>
  </div>

app/views/tweet_clones/confirm.html.erb
<!DOCTYPE html>
<html dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>投稿確認ページ</title>
    <link rel="stylesheet" href="tw_sample/app/assets/stylesheets/tweet_clones.scss">
    <link rel="stylesheet" href="tw_sample/app/assets/stylesheets/normalize.css">
  </head>
  <header>
    <p>今の気持ちを伝えよう</p>
  </header>
  <body>
    <div class = "container">
    <h3>以下の内容で、送信する。</h3>
    <%= form_with(model: @tweet_clone, local: true) do |form| %>
    <%= form.hidden_field :content %>
    <p>投稿内容:<%= @tweet_clone.content %></p>
    <%= form.submit  "投稿するする~" %>
    <%= form.submit "戻る", name: 'back' %>
    <% end %>
    </div>
  </body>
  <footer>
    <p>Copyright © 2020 SHINJI ONO All RIGHTS RESERVED.</p>
  </footer>
</html>

app/views/tweet_clones/edit.html.erb
<!DOCTYPE html>
<html dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>投稿編集ページ</title>
    <link rel="stylesheet" href="tw_sample/app/assets/stylesheets/tweet_clones.scss">
    <link rel="stylesheet" href="tw_sample/app/assets/stylesheets/normalize.css">
  </head>
  <header>
    <p>今の気持ちを伝えよう</p>
  </header>
  <body>
    <div class = "container">
      <h2>投稿を編集する</h2>
      <%= render 'form' %>
    </div>
  </body>
  <footer>
    <p>Copyright © 2020 SHINJI ONO All RIGHTS RESERVED.</p>
  </footer>
</html>

app/views/tweet_clones/index.html.erb
<!DOCTYPE html>
<html dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>投稿一覧ページ</title>
    <link rel="stylesheet" href="tw_sample/app/assets/stylesheets/tweet_clones.scss">
    <link rel="stylesheet" href="tw_sample/app/assets/stylesheets/normalize.css">
  </head>
  <header>
    <p>今の気持ちを伝えよう</p>
  </header>
  <body>
    <div class = "container">
      <div class="tweet_content">
        <h2 >投稿一覧</h2>
        <%= notice %>
        <table>
          <tr>
            <th>タイトル</th>
            <th>内容</th>
          </tr>
          <% @tweetposts.each do |post| %>
          <tr>
            <td><%= post.content %></td>
            <td><%= link_to '詳細を確認する', tweet_clone_path(post.id) %></td>
            <td><%= link_to "投稿を編集する", edit_tweet_clone_path(post.id),data: { confirm: '本当に編集していいですか？' }%></td>
            <td><%= link_to '投稿を削除する', tweet_clone_path(post.id), method: :delete,data: { confirm: '本当に削除していいですか？' } %></td>
          </tr>
          <% end %>
        </table>
        <%= link_to '新しいつぶやきを投稿する', new_tweet_clone_path %>
      </div>
    </div>
  </body>
  <footer>
    <p>Copyright © 2020 SHINJI ONO All RIGHTS RESERVED.</p>
  </footer>
</html>

app/views/tweet_clones/new.html.erb
<!DOCTYPE html>
<html dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>投稿作成ページ</title>
    <link rel="stylesheet" href="tw_sample/app/assets/stylesheets/tweet_clones.scss">
    <link rel="stylesheet" href="tw_sample/app/assets/stylesheets/normalize.css">
  </head>
  <header>
    <p>今の気持ちを伝えよう</p>
  </header>
  <body>
    <div class = "container">
      <div class="tweet_content">
        <h2>投稿を作成する</h2>
        <%= render 'form' %>
      </div>
    </div>
  </body>
  <footer>
    <p>Copyright © 2020 SHINJI ONO All RIGHTS RESERVED.</p>
  </footer>
</html>

app/views/tweet_clones/show.html.erb
<!DOCTYPE html>
<html dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>投稿詳細ページ</title>
    <link rel="stylesheet" href="tw_sample/app/assets/stylesheets/tweet_clones.scss">
    <link rel="stylesheet" href="tw_sample/app/assets/stylesheets/normalize.css">
  </head>
  <header>
    <p>今の気持ちを伝えよう</p>
  </header>
  <body>
    <div class = "container">
      <div class="tweet_content">
        <h2>投稿詳細画面</h2>
          <%= notice %>
          <p>内容: <%= @tweet_clone.content %></p>
          <%= link_to '新しいつぶやきを投稿する', new_tweet_clone_path %>
          <br>
          <br>
          <%= link_to '投稿一覧', tweet_clones_path %>
      </div>
    </div>
  </body>
  <footer>
    <p>Copyright © 2020 SHINJI ONO All RIGHTS RESERVED.</p>
  </footer>
</html>